[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "9f06d913c5036f46069627355b2991f8254331ac"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "1fd2036a7ce577ad09c699cb5189b29e4b27d062b7b77c02dee5f37dc95abf43"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v4.3.4+0/Libxc.v4.3.4.aarch64-linux-musl.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "f47224e0af7c5cd40c35116ec26ee67cecf2c4ca"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "ac9e2c9ad16fbf27f5ea86e52973a2f821217f4fb8e2c84965654b492dc0350b"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v4.3.4+0/Libxc.v4.3.4.aarch64-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "de61f89b3947c0a4e375481065160891a61c43f9"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "1afe125f985d270276263713b2665a2e1b78d6d4fe55ad9b261c9023a9062235"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v4.3.4+0/Libxc.v4.3.4.x86_64-linux-gnu.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "37cbb7d99978fbf0d3519a36b7876b6fd8c6bef5"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "1674c2b484ae9bb4e5c7a659606ee9689bf97685ac55c90e7059ae05e3a290a8"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v4.3.4+0/Libxc.v4.3.4.powerpc64le-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "beacd82a59e2140128f6e0532ad287ff3b5cacda"
os = "macos"

    [[Libxc.download]]
    sha256 = "c806dba9649d68c486122986f7e6f6e20284a0037ba2c8602f34d3d0db5e668d"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v4.3.4+0/Libxc.v4.3.4.x86_64-apple-darwin14.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "9f5de43de97fbac84a4cb927f9484c0399f3a137"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "e51f926b2065ea2add3efab28bf6f2317b89bc064247742d5c3095b1abc4428a"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v4.3.4+0/Libxc.v4.3.4.i686-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "b77367abcb4975d2b6a2f98cfb1ec32e300fb794"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "3a92aadb6d7844a20480742e5fe0e3d81f2203ac5e6894794e78c09684a5baae"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v4.3.4+0/Libxc.v4.3.4.x86_64-unknown-freebsd11.1.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "f5d71798b93013d41abe73c655a8c5edfbcfa5ef"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "636cea60b8a0651a1c593d9b994005a71be018e255d691db5a5ab3b3f97b6ff1"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v4.3.4+0/Libxc.v4.3.4.i686-linux-musl.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "44fcc4aa537f38acac4ee04d6077bcf10fb26801"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "ec2e56b21e9217835e2ca3c77f19fdd272229ca7aa2adb9e05b8faf341176d20"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v4.3.4+0/Libxc.v4.3.4.x86_64-linux-musl.tar.gz"
