[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "ebd87c44aedcf15ecce800b8ccf80153a180d4b9"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "41732a93ad460627aa060e1350eb9cbd39cb8f681203e80e4fb2a459491681e2"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.aarch64-linux-gnu.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "da08aed5cace3ffaf1fcff8b97a39c4421b45321"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "02a557a11f9166991119a3ae51875599ad6c35bc46ddd4c00cf9e47dec26fea7"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.aarch64-linux-musl.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "df97b6a4ad08ce665fd4486ed3de3ca576061797"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "d711989c250d5f99ff84b74f0ae3347e5dc592dff73cc820754e4ad527a97518"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.armv7l-linux-gnueabihf.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8fa1f1c394ee34f2abc98b94b68aa876645f5742"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "c7a03933a15ce43eb093ba45eff52016e523f8d96cdf2ba8f0b5f3d778bf5d88"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.armv7l-linux-musleabihf.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "833ba48f575ca79d31a1b002fbbe6e2dbf751fd1"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "8ede7f36938a4b9dcd0c9b624b07544935a48847182d3a6b8fbaab6d0e9598ab"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.i686-linux-gnu.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "366ae34adc400d116769ca22c91655ae061c5e63"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "992fc31f26e18b3d72436734252b751a71d7c6256433b3164826225c87ac67f2"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.i686-linux-musl.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "f95c4b6f1955305db8dfde0b915695c6f7007f24"
os = "windows"

    [[Libxc.download]]
    sha256 = "35dab4856c0bb8d2f1722011e220482a5e6aa721591e254de1cccde743150a42"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.i686-w64-mingw32.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "34f3868f2be6938f6df44065fd923dcacf5b594c"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "277025388e24f0cb9362eb13b528ce16fb34e285323a0849fd743f572515d0eb"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.powerpc64le-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "7a7d632421b4fcc9263ac8104b10bd7422ba6495"
os = "macos"

    [[Libxc.download]]
    sha256 = "972e66fa1f2e6bfe22476e65dd7e52a6cc03a04be2e87126ca97ecf75c646e92"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.x86_64-apple-darwin.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "695e6dbba28f3322f62e2c2f2633e21f0709b72b"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "5724892ec0e63fa8f97fef344f3f1290ce44eb77e345c9ca4d42376d8debb3e0"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.x86_64-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "3069371f6ffe45d8386d8adc2e42f844576ac1ad"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "754ea5e328a8a95f00b180b38d71b6347aa1eae944508c360a46bdb54cbd2af5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.x86_64-linux-musl.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "2431e8eefc0b3d8d7108b162aab4fc99d35dacc2"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "8ff9f9dbc9b3551db29a6cbcde657bb6f4c1fa9ea941504b09a9a59e8e5c8a63"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.x86_64-unknown-freebsd.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "fd5afa3e3cd90be7903646188a204835c3f2f3cb"
os = "windows"

    [[Libxc.download]]
    sha256 = "a05218ee06f13ad7a6705f4573fe907895e25b93e0d234318f8fe2dc578a46d7"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.3+0/Libxc.v5.1.3.x86_64-w64-mingw32.tar.gz"
