[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "ef5ce03e57baa11de2fc5767707b1a10b4d5ba22"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "d5799bece763d67711be22ad66a1efd1e4be564d1407cfa51054b3b814e624c5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.aarch64-linux-gnu.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "f6d7ed1a227a0f5a82279a2b4d9d926b240fd99f"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "852ff5b7317c6d17b90bb5a01559e3da7cd2f8faf653c731539f424d37729968"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.aarch64-linux-musl.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "76771eababaad0579970fa2528ec19fcf6b17ed5"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "50e490058f9ddb4a90647791666eadb2e988fa79308d37fcfea92c5e8f0d5e0e"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.armv7l-linux-gnueabihf.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c18a7ddf5b42a7fdb438cd9da7c8581f7327c380"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "d9021893b81b5dbd60d9c3daa44a27a813786cfadb68417efe5701f8d0accb6c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.armv7l-linux-musleabihf.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "4f10aedbfae6ff2be706e00c0a7d2abfdff8458c"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "00e327b6597487405cfebed361e0a493c58d0847ecb97a6c2ecd2e04818a2049"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.i686-linux-gnu.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "40a55fc7c08d7fe859c989057a54774e80a7f050"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "60843716c5e1bd36bfbdeb6b60a2fb69dc8d848adea86b905f3f374e551f9958"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.i686-linux-musl.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "52f34de0be20547443d886232dfdee6a114ee9fe"
os = "windows"

    [[Libxc.download]]
    sha256 = "8418506c851026c5a1f31090c2b31596bb4c7b750a33190e0306f26053717c37"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.i686-w64-mingw32.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "fcb15e30e35e8fbddabcaef31644e472413dc0a0"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "4ba34c805f9998c6bc3466e504afd521edf1663e3f58e4d938e8bdd4b2f2619e"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.powerpc64le-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "7d702d4f306f67bddf60868ef4b4e086ae86601e"
os = "macos"

    [[Libxc.download]]
    sha256 = "e9c1893ab98b1bd03cec5062a1f2ba8de85fb80845e3ae34d7ce4813325daffe"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.x86_64-apple-darwin.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "1963ebebd3e6f9546929728c8304063e8782f69e"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "dc7209effe3e26bfe9d64a4935c1bf217a9597bf03b8b79b7f864bb938b814d3"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.x86_64-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "524565507bd04270c53c953a0a17fb2b625c515c"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "92304d155cc8d2dd42f7c11509980fbc9b3c1eaa10bd2a89a9e92cb4411690fc"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.x86_64-linux-musl.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "e1756989aafd3c1d9b52615e529437a3d395eea1"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "c3d536b4360521c79a51d330a8c543ce4b4f62f4a1ca6f6c56452ed84cc25132"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.x86_64-unknown-freebsd.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "5ede4c8103813cc4eca4ddda2fc527314c961272"
os = "windows"

    [[Libxc.download]]
    sha256 = "59bed0e2059596e33df5a6c55a7f51dd807c8649acfa1f7cb1287e82229e85c0"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+0/Libxc.v5.1.5.x86_64-w64-mingw32.tar.gz"
