[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "31afa747b2cda2611f8842bc21a4a1aa7a45356b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "8b30c1cd8a74a76a1e63622690bb2b873dd538719abc95e18f0dbb65bcf39203"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "ba4354bb32359c2c05738f01fc8ecf9f67e13f53"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "581c357c4b2e6c19e9bc836b35a749a5c2e72f71c476442812db90405329a418"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "13198e396da62c2a2b916c0352fb62a715b8bb54"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "b69f13fbc251f42e3876dbd367915ef4f6f3f1aa88e606173c7171c823ba66fe"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "a3e552480f9fbe68995e6d36e2f3df31d3395212"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "5ea5f795061a30b379e0f5fae46e6f12eebf00af922c252b8f36f95fb45f2830"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "a43ab41cec6f4b588f2433d554f0032fa3192add"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "18cbadbf95f7ad705d1a0fcd613c64567db144a5c35b8e79c02b14ac3b406566"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "08dbfbc5a85123bfa069b88037fa33150a82c22a"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "8a3312bc4e2dcce3f0f6e880e9247253ed2434053460d49f0267bfaedca67acb"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4784501e63ed3fd50fbd888a1478ef29a78efc03"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "2c76b83658bea25d0fa76d65d37c74139b4822ede14dd4ed76ccad4b9393f154"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "32a2473c7d1def7a4e54f92edd2da0bb39e6e477"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "ed51ec62b30c9512306e1fd64bb90b7801c433375d30bc3b13816b6b1e02df23"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f4a40b28a266c5a918ca771464f1094374b47da7"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "7e7b059dbc01fd4247202a7918b7ae73e00c39fe59801df752e9320879f4a949"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "62a31742c657ea6ce4d7116023182e48eb5af4bc"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "71f835567c060caee6a048fc27bf9fcfcb6661df61fdfc6ae295fd655c3b258c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "a253ce80b315eaeacb63883f24c7882d04e3d8b5"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "49d052d5dbafbc3be66deee0bd5eafccfd489f6766209f721f17ea14ea466b2c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "12b38bad5eda387b4442455e6fdff0cd27c85146"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "b6f27740d13ff427a4c808d1bc74d4b66febbe666d054bb84b2873e3add39b7c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "1049f6f44200c21e0e9c78c452dc17293f357530"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "96e9fae9649626c1b2776bc97ef7b02b2f394a253cf7ca195a1cc094ef021f6c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.i686-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "6e4df0496150111783556c45568ad41977f6bdb1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "d9db5e0328ccaec279d8eff90b73872d5143c46ac31198eeace5c96c903ce003"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.i686-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "70be93d10a23dbc5ba23d90273bb12f3e64f1265"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "d63948ea779c7c7501af21f875bf4f8f9648b0eca564ba7fc59a48cd6298fe1f"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.i686-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "86db5fa6c780d60a0c6981f9703c1fceb83487eb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "6186b215ad90c78213086dc2e319f60e21d7ac8014977f7fde15e4819521763a"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.i686-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "dd7b6bdd9eae72f96519ac1d7f6dbe805f1fed49"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "21ea7e2d10a047a28fe348bc37a2d89aeec5283910c9172c4bcc9490f332f70c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.i686-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "2e23b33f04662252bb7d140ff2d448c29e96b17c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "c71b6a6ae28c94f5b76547cb73629600fb0bec57845d3ea763e691b87d65d03b"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.i686-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "f2fc50c3372c35dd514df17ce69c151fcca1e670"
libgfortran_version = "3.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "beee27835b8bb7b2dd4d14552531bf382e12f6a4aa7cd003cb1214dd8d0a4c90"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.i686-w64-mingw32-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "e6d39e62ca28f65e6d696cc16dc86f41fee70695"
libgfortran_version = "4.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "772bbf7010d591267a32e26bfa94f0abfefe797362c2ced88ec1f4459ff98cf6"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.i686-w64-mingw32-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "a812c6467f6a08fb38dd33e3f3875e5f9ac3e9ed"
libgfortran_version = "5.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "947e08f403bba39e8b0f96c7d915415cfc8a354f0c1ff1cf128b9ae9ef85f001"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.i686-w64-mingw32-libgfortran5.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "047c5ea910a9167bc913936722ce01afe5b7ab7f"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "727767672ee3701dc043a8a1490ca42437c348777ae0ac836ce74c1e7a3ec870"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "15b3b22f9ce89d88d65c763a2f3a3a745ee6d8d1"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "03cc90333d3bbc39ae90959e20a5d4180509ba2a10c44d45fa261aa030c80554"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "769cd29331fc1417fd7c6ad0402100cbc04d5c9a"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "565434cca4d283a04c71daeb06c2d527c7065357fb1bd44d6b70a3a342304f95"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "b9d99d50d7d418b13cf2d116bcff85b1cbe3a595"
libgfortran_version = "3.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "3ba75f51a213c1ee9b82a54e4641d9e60eb0bce0edad08cd404e53ab5cb98474"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "fb72b11e58371cae1114cc2f4b0079af75b4503a"
libgfortran_version = "4.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "03ec809db18fb53de399d58b167516691ee9291e16f0a8eb81ba1863131b94e3"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "2fe046fc9bac9aa2c6f30765b74975746326f96f"
libgfortran_version = "5.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "0503df71258bd9caea4d7e0d3068477c0f4b9f7abe4b917d9af1623a6c2d661e"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "2b7cd9ed6c218ca633a518fc2026fe5e158751ab"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "40508731000931e0af128b1705b7fef25d16542dc469becb4d2a4530dc4dee61"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "3da7aa83ea1c50f4184406ab4ccc3f3401209797"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "cb6e46701179ea975ba596622b7a2a17eccbc9d730a985ae41e9bb23aecbb3b8"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "2be157c09bc933c999933fd8ea2b965a7115bc5d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "e23a21ebdbb1bd3d496f6f9b4bb5d4b73174824d317fdf3857bb18b1edbaa5b4"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "2ef2a29199af4c08b3ffd0b55cdc6a1feca6b183"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "9e9dcc5a6f043da798292a61fdf1fa476d62145215f9e0da5b7076ada5fa7d54"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "37261bd0e42da146ead7ebd976f8e1ee855c435b"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "3e6a1a4b2b689265e7bbf12701d4979bfa344aea551c52283b7ac5703d229fd7"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "a7ffe92dc846ae473b65080967857fa6999f5b04"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "902034898bc928d05c2d958bd79de7bc62d50cf50aad206867b04f170d7ee184"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "fd4dd844d0178fda5b407092ae7a7786aeb4c6cd"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "10075d60b9aab800baca45e6e2f22481cc76309c2a6e00b09c506b70bae4309f"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "f6d8df31c45c7e8fb072790cd403143618d358a1"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "361eca8852fbbd3ee56efe9e65268fdd176e4a5cc4f1b548a4c3edc088c57c19"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "6c640ff907a82f226ee4849a519567e533368946"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "fb7200a5fcd62fc04c0fb324cfab773e8c7f134586d42d57cdc6cbd97dd6d9c1"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "e878b1e190c932ddc154cf7479ceea8d925ad628"
libgfortran_version = "3.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "d4833203d750f64559673e24125af8a786f11ea622fa265277f313090ad70cf0"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "3f67f7241e730c4cc06127294781937986c6f7fa"
libgfortran_version = "4.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "a06035945becff95009d0a89a7b7f48445dfa60728d3d96d8ee5e126a9e20e76"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "7df3866d643cce220b6bc10c3fc75e7a1faa4703"
libgfortran_version = "5.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "8c4f57ea392e4bf02afd4aa1b928cfa8037f3fb9c7b3082d749b43c76fa72db5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+2/Libxc.v5.1.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
