[[Libxc]]
arch = "i686"
git-tree-sha1 = "f48f2d1e8a1a583ebfa34d28d12133c80e3e3878"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "93fc2c21e274dcd10c9508c9d38a6d63bd274f37d603cf06767a5c58cdd77439"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+1/Libxc.v5.0.0.i686-linux-musl.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "1cb2db58d923e94579bd6cd84f89928415762638"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "40dc7bc8aea83d0ce1851127d6a1f0b26c4dce3ea6c793b8c9c66be8338bba09"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+1/Libxc.v5.0.0.aarch64-linux-musl.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "399f5f83934f186383429b7cdeeafb904bb3791e"
os = "windows"

    [[Libxc.download]]
    sha256 = "f493a9bb3e438021f9670f911638de7076a660d707f2a89a81996fcd14647c7f"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+1/Libxc.v5.0.0.i686-w64-mingw32.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "2dc074a7e39f91c6084fdec0cadb0da23869b5aa"
os = "windows"

    [[Libxc.download]]
    sha256 = "db6b828cf86c218245335556d003cbc8605259c9ad29787168425a90f37fc9ad"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+1/Libxc.v5.0.0.x86_64-w64-mingw32.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "02ebd79d76bdc4fd78d7122199e9a02986020868"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "a118a1b3218d7c602a56d8a1dc40ef8fb7e77c5fbbe624f62a011c7c6919f2ed"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+1/Libxc.v5.0.0.i686-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "7180a8908a6c8112d1b0402934f1c2dda380be7f"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "cdcbb900524c84f3dafb3b0a67942edafdda4071c6c5e6e877d2c83dbaec7f2c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+1/Libxc.v5.0.0.x86_64-linux-gnu.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "721daee947eb26d445e02b95060bf297f0731730"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "cbb48aac4f9e9c8a8cda44408a0be76a6a91d5358a28b9c9d3ea0587b4659d99"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+1/Libxc.v5.0.0.powerpc64le-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "0623d3064afdd809b4d38fce848ac5a5fc0b8095"
os = "macos"

    [[Libxc.download]]
    sha256 = "2d8226e704a314b778c2f5d959860d955b3ed4c28cce05eef6a6fa0c623855c5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+1/Libxc.v5.0.0.x86_64-apple-darwin14.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "cf3a2d3187d648c1a30530798f2d8ee70416e9ae"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "5022c94d6abfe0b45db27a668a7ac7e8c668fb58b02da767823c17ddbce2baf9"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+1/Libxc.v5.0.0.aarch64-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "faf2d464b7cff3814c1361a1feff6ddfb18635b1"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "d162975a8ac753908f98a478b8a192575e43630ddd990fe3cc0d63f33b78dcd2"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+1/Libxc.v5.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "323714f65958f0623d162f758e4f403d3a72f26c"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "b9eab596b30caf11b810a659f1e89838b5a3612b33eae809e942af13fc51cce9"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+1/Libxc.v5.0.0.x86_64-linux-musl.tar.gz"
