[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "25887a0a35edde75e0e1d83748cb9f263456264c"
libgfortran_version = "5.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "b55d1bb8a28035b557dc48cae278b55b514db5e9f5efa1d4f7287169db825f8e"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "22aadccf21a97344969e3c0b5a4ee77c7a2570b6"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "29dc19b0efc0eb12fae2b3ff20bbcff7391fe2b803a498e0896e9b754aabc655"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "b7a384a09e325188f846dd70abf6758eafc9123c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "439818e7f743c9c120a81f5eda6f8a430da67eff9480b032e59970f434de7b66"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "11219612cde684c9afbc5634b9ca90fd56138c31"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "9a0be39e845744b9f2890b062805fabb0d3dcb0080fa2155c8982e0fc7bfcf06"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "71df88d649e36e4387aee037072e5fc953c5311f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "423118c8c8334962bd6ce662d1a01df9e2e0e6cfd8b9ab8897cb30a1ec6ba81c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.aarch64-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "f229a1c9b581ccad6a593e07c024b263f6e5ddba"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "7189885230fa8057b58dd428dce000f51679649242b9718c0f1578eb7cb7dec8"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.aarch64-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "038a9d3e4d2bdacae2dc4115ddee6dbf0a5e8652"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "a3d6fe346cbe14b0610eabb6a67779c2ed35a55a1b3dfdcbc0f1ea4c51d47b21"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.aarch64-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "aeec0aad633fc777e1ba57b37bd27cbc6b74ac97"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "7d431805048a006f076a8c84822da9025e47a2f762ac7ec9cf0574cb821620f5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "fb669b1c269f00645ea6acc9d156929d96dbd5c0"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "f5b1999fb84b31a9ba50c50c7d79489099ee4ef3a5ed1c065edc7a63469146b4"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3df3f9b34419b391b89161fc518b7ff6ac321f34"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "edd2ef77eb5dd93fd6923ef791a0748563e3cd89f104ef1a60d18bf7f4b6e614"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "81ea93df35dd524b18fc962a18312709099ee08e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "b1a2adfa8cc2af87f7124ddb59102ef66796fe167d46010dd143a0685cbdf9d4"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "4cc35577cec21097f1146e9003ff273bca832ce3"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "87cf59db36ce744f027ec01d9dc34723bbb13ec0c3846d44b3988af6f4773e55"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "94f906693897d040cea9ef1f2dfad0a77044afe5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "f1ee168d2c790812b5c222c97df00a0ed3707154bfd0810ae71db9f457a12c93"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5fca90e8f926ef3accc562c1a7fa4c2d7289957d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "0c2401fa414f97fcfeb9ec6415ad0fa1f22037a8781ff2fcb01d6e4a2f605f6f"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "05cde50e377279b6c98feab9ffaaaa4c45a7db75"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "441c2ed3d2f2bb10dc89b859b2b6920cd8200266cd1c0dad0cbaef0a06747261"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1a61ef4ad37d574064b9ff4aa340fa92b28a8da8"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "3f73ddc365398444b2ab14533a6c95d0387937b646249a01880f9e02ab7e4242"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "c7b6dce833aaa6e1731355d693f668ae55ce94eb"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "63aaa9ee75fcc9f37869b0fdc030c4cbbcb76f69b8d9182c3ebfa03f9020b7e0"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4b936d99911aad2b73a3a55f740eee7a148b3964"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "9819d4a7ec0a4e7b5de47915a02a752fe58f68b47512ab87e0b2f33d5d2da344"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "583c024e475cce8e99a5851ef632b12711d4bb43"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "82b5846ccb1e96c99d25a26115d48453b473754b81412eee44e5d9634d566d03"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "c4c386d3c211902cd85b7d3f7c42bd23b5477a45"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "94f55ce50a6312a2a39a2e6c82aef59303fc3bf04a05c985aeccdfb3548d7168"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.i686-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "e08620463742ce745bdd82b4b7dc74ca994ff3b5"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "050661267666b3580e7e6452a43b6839ed1483030e52a18706207f3ae7599b10"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.i686-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "e5b4f278017a6c72c598958b8437befff7e0fb08"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "97398640d0849ab3640c8a4b1aba537007bfc9700192ca897573efee51b085f5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.i686-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "c37b4cef15fca5f477041c3330879caa4f15d241"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "5eaa359ef601fba55b9ceaee28aa82f1289dd17e2baed8a5622872355de20d04"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.i686-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "990834d4eb5077238fefd7d98bfb1147cb7ebabe"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "ef1d596c9a29d897b069035d648abca7be05fe8c8fdcee9c32f3e3c804a81a9b"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.i686-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "33e1da6e6629ab75d31bcc1eec6730c4f9870d3b"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "e3862e70e11107bffa13ad164cc78787589778902b871595cfc410d2f6bf098e"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.i686-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "cdc2afcd5b3fa9f588eebbe8f4f23ba142766b11"
libgfortran_version = "3.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "039b92905e22b01f3d2a5e343bc4a1f87da7c466c3c425c91bd647e7a6bde26d"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.i686-w64-mingw32-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "c8014d94fb64dfce2844dc3770e6dec210992af4"
libgfortran_version = "4.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "bded28cb4c80c5bbe9576ad07d20d94ab1f31202a0a4064dd959bdfb176f3504"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.i686-w64-mingw32-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "1b0c615e7d06e291832e14413a9d5449561188e4"
libgfortran_version = "5.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "e68b9682c2efaa283c7854fbee3c38cf3855f667a15ace5fa0d825569953d6c0"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.i686-w64-mingw32-libgfortran5.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "4f2165b5dd3a7e49af87317aca31959953673004"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "8ab77e8a1a20b6b1b19e188e4ee1d49583ad8a2ab5da5abe0303afd63d369b24"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "4776e0376e8659d0218abd4ded62b38a0a1c6dea"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "e4b54c476f7c517b8bc520c03ea87d2e422707f69fc9d7ce10b75bb1584efeef"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "ef73f0c01905f7e32cb6f7279847ece51cd961bd"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "7a3ff787a3c13cecd6e689ad3fbb25dcce618d68004236d72382875951e0dbcb"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "8077c9cf0af558be3018bbb3d1bf0ca0e65513fa"
libgfortran_version = "3.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "b676c26409319e998bac1e9f244ff52fc92dd605616771d39fa329c04f66c75f"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "59e5286ab9369b4b1e21c417f249a52328c61287"
libgfortran_version = "4.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "b192c2f74d365437c9a8cd874adab399851d3d8329068c53cf45a6cfa682187a"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "cf5623f6ca01f95b9dd01452a994c194663038b0"
libgfortran_version = "5.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "f243173b21065802b8e9492c2f6ec2acde79eb922673f104786f174ccb5f8179"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "a0d339b4e41f95043ab7575688601e601736ea9c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "9540b1271a230a233ae9d710fc217a4a50fd90b5e4a5cabf9bd0811fe152f824"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "587982ea553b42881424757b5039635ade8aff4c"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "55b47a7aa8e315232762765948c48333b5700257b43effd525b9dc914634ca3f"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "fdb15be472de64fa23d256386de0019096a9b15c"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "df832bdf06fb2eba75de7f39cf7982fc84c2347949deb3ed2330296f4477cee0"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "66504d4de2c992c21cdf606715882054dafd2796"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "8bf0ef88023d84c7378b1af7e82f6f6dc75a807acc18f7268be3ef5a8e869fdf"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "234eb79719ecefb40e0569624064942b2ee73845"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "aa65ae77239fe57a21a8831cab7b0575b4062f10caf76a946a3ddd065fe5b358"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "d0a291d05bc59c8c3a99a5d65d4da97f8dcc4ff4"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "6abdfc13ebd9afbc09ab2e2404173e7ba0d4b82db3378c81ae68c5f3569e79ce"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "92f21422973c314373dd208b43d8250b6318ae15"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "663af22fdac7357b78af111e502f2fb2d988b6b903c654bb570bcfe977d0628d"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "cb99cfcd5a24e371a407be7c785d050a0b430ad5"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "c3ecc7e6b0e96f2088a8537a8821f6657500dc7236ac461b5060bd65dc96187d"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "83f4c6451ce06316887970ea646c2ac0458aaac2"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "80a4184554a2289c44d6cdedbabb0ae7cf288bae844b26d2b7f510a734b7f5d5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "9d43536ad601a7329401d2df64d19e3e6454d122"
libgfortran_version = "3.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "a1bb804957144beb51eccf8f0b6623e41f2abf983826f7381171b1a7a78b05d1"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "c7292ab9ac8e1e99d0271089afb319828f19f13f"
libgfortran_version = "4.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "fe890f4fd2498ce5f633ca1ac87f0fef010a24dcede3ff83c29ab3fb9020d80b"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "f71e003f1175215d92f3f9f7bd1eda5f9c3869f4"
libgfortran_version = "5.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "7a8a77f45ff9f0f5f8f788eb9491810e8a4698ee93d23402f1c02561a7914bd2"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.3+0/Libxc.v5.2.3.x86_64-w64-mingw32-libgfortran5.tar.gz"
