[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "7de289bb6ee2fe9789414ec12e40cff412a2ab0f"
libgfortran_version = "5.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "80d3261c20084aec138b58b55a01fc306d70a05a9639c28ad921d0b588ed62c3"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.aarch64-apple-darwin-libgfortran5.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "6e2878d927b29d4535d146c624023bc5ed837b4d"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "792757b5297ddc8efc032c7f640db86cea61e69f145dd6d297afde0153cf0bc1"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "b17ea2fe9924abc177a1662d5af7714d42e38f01"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "f2696c8bbe8206a0b9ec2e51027d7558bc32f15377a11abc066ac525b8ad81e9"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "7d38c607c7aa57bd4af3f268a63b1cad43fa8851"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "724eb62393bc6f8aae08ac1c08f280723d0d7917159427832d67803734ea5381"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "18ae637f5b2f4137b56d4e1b013b6184938f4b05"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "cb020aec7ce28557dc4f332b6c562c7a7693af69b4e7ade3aa44735fba7153eb"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.aarch64-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "3ee43bba342c6f3d33d4264e1ce6ff8919450bcd"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "2e0a51b66960af71d4ae5fc71a1e4ca43f20a26566db3bbba0d7a092d412ad14"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.aarch64-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "5c9a0f73444a6100d936dc045ea7662dbd1b5752"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "068d305012ecc0eca293f04722e1d1c94f4bcc2c4b07b121fbd6345b0ef2329d"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.aarch64-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c23389f46f0b904fe97b282d3665592e10b94a78"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "06cb470f79cb875565e99e8e402a71cab49321f2bbb6a843b190f1108ab4ebef"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv6l-linux-gnueabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "13d3a803905161ffaf89ed1ac3fd4a44d5229c50"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "5bfa94bd51524b758b135f48eb602fd3c836e68131d4bd58ffea6f98facaa1da"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv6l-linux-gnueabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "52e2298e070f1d5161dcecb4718d035f94e5fd76"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "2696e769a8f2ef9ae058e1e8947b56c2cc933f2f5d827a54b877024b6cb8b652"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv6l-linux-gnueabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "17927dc142f0cee4eaf3828b63729f6345b82606"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "8d157fb89ebfd786094f2219612d73b1cd44bac84380bdde4d8009a382069625"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv6l-linux-musleabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "be30058110bb92860e5857294581096f3410e7b0"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "34ef76418c255b9cba0ac1b4b594a6ba86ccaa02b4cca9a28898d6662dab8f71"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv6l-linux-musleabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "c7d0a2a2fb142b101522678b7cf9cebfc56c8b6d"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "e9d453b86d864aa8198dfd9e2bcd31dc601bc8b2cfb32427b0a369b2b8296161"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv6l-linux-musleabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "f16e11ca492d48ffbb976116f4c02372d457c84b"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "64e8a12202923b98559b2ef634deb1b236c4855cc139bd70af0dece69a52b243"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "06a610e7a634c3a22c78441b2c0e3de286eb8341"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "aaa161a361a9098e0754fecb2c8d8632c9b162567299edc5758797c79d5932c5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "17d42946a9d4120c7aa76ff787b90d1e4f0c20ca"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "c6d93fb64849e927bd9d320eaa48b340c800f5f3af6227c53b2f05fc759c3177"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ba426a3d287b78a114d91ee44f43bf37b49917a4"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "d63e665ba1cd81e9521cc926f8c7c2d8a0d8a2239b866aa02aa0596918af05c6"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ae75b2a8764c79b7d49422cb2efdf2c6f4c3ed80"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "b994e556f45899ecaa34742c83fa7ec07ae084b5bbb628b3e46f152f931f046a"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "cb910db45918bf3bd75887cba94f52f46881d66c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "30753aa532a8e61ec5b0d855f356038d18e2049ea8ab3627994a811c262569bb"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "6b9e087024c2d12fcef6edfa9d125320fa730b2c"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "e70000e74562ef500f47b59cb00901bc9a73ec88193d5474827af6655eed899b"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.i686-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "bc3e66acf0d5d86699a506268d6dfa4aee072427"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "39c83b6e86c9c35860ac6b6171bc84a9bacf1e359e3aaf51079bf02a893d0ace"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.i686-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "853154c104c17eebb2c57f6498e2697de3afee16"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "e14c5873faf8598b29696cbb19e5e4fa01e56ed96c6a678c3d6cdf092dd67c1f"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.i686-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "7548c5613b1ab86dd89df9b7974c29d286299db5"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "d9d0068f636fafcead94aaaa6a0013f0697f8e8eed7b39161edbd67ac674acec"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.i686-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "c9c9890376412287fbd632d8f0afaeefcc8cbd70"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "afd49d053843524336a5122a55b66a022a1bcaf84af5b54857efc98aeb11e60f"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.i686-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "d701277e425892ace086187e2aaa8690871c0c19"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "da03e33e71b509219b6dac20ccb705887ea4497a7f84262dab51bd646ded0f1f"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.i686-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "167903226971db15adcc8edaea69d768543a8ba1"
libgfortran_version = "3.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "92911e198d9d208abd779227c52b18ea02b87820d605e4009eb292d5b0483ade"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.i686-w64-mingw32-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "3335d0e9a9dfd760dec577ade9fa95867f441475"
libgfortran_version = "4.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "e7e13509cfcfc330146f39d0cd0f3e722b05582ba8d8c38cc86eac34704f6c35"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.i686-w64-mingw32-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "ff235688fbc01b347d1bac0fad8df41fc4219e65"
libgfortran_version = "5.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "5b94b0e1e4c1f923d2cbe4ee694668cb56273406267231fa2e9bcb8ab0a589a5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.i686-w64-mingw32-libgfortran5.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "a2341012d9aae97244985fd8d03d51315b925ef2"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "ac80f84a3e3e616affa0fc72354d507ca705e70d28f5dd07333a601cb6056ed9"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "c033c365ac6c6e5d653e7ac60c3a87a48f990686"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "fa1dee1b548c36dbfd2c9c3276f8d477a276130da46fa1d20bbd7ee2edd0470c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "26718b4e66d7558c4a90dfbd3250ba3737897d2d"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "f0609b06c4f591457f0d496a72419eff2d0c82afc5fae479dc985c2d5a5357ba"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "d01a74040e8428a9cd11b8db8f6e49441936d0da"
libgfortran_version = "3.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "1ca23ecdc9295045496a33b398ed220ba6934c3f93da7813e2af81156b05dc91"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "c13e5d78d33d2ab464a2634200033b44011067ba"
libgfortran_version = "4.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "c0aadc302f0c1c970ba9ab48f00a3025ddd018d3ce5abc460da7c520ae1edc3b"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "3a35b12e124c7eae11db47432dd3c69f80785bcf"
libgfortran_version = "5.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "88c3eb13efaf3ed715b3e3f5deee0fd516ccff45384e03cde2b462ba7bc29984"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "1dc1fd88a0d451122645f744ad0382391e0c9efb"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "6676db5fc69121325e0e1e2401027a8d0ece79cff7d00dba1856d5ababaea6d5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "1e4f7f4856855b10846b22a289a5bff30acfc36a"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "4b4595e2819a0f106b28e4c85da843c6cf56b339c455cd1b4c30eeb510bbc833"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "203988e87d9b56423d52c7719fbe4b8cb832e716"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "2d2abdf5255d9f0394c30a36f70f35c73be022073bb3cfc6407a4db559961905"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "94f17770fb9bfae75fd3bfa7d228be3a68a0e63e"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "0a4914ec5ee3c8e6c41c946be55a699189bc34e33f89dcede2e9df79a02e0416"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "751c76707fed932e608acdf5ac41dec2fb048ecc"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "2c3cbaef3541fd1645daffb56047c2520cfb8ca34409a91d28dd46f301f2e02c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "f0285f3f2071056d38e79f807dfa36d09c03e04f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "bd96473acae42887a8c83bb0d4ac80b9ab59325fc5ac7760173e608d04af1d99"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "75821f49b3565577cddcb49923fd34dec93286e4"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "2186581885ce7d0e7988f8b7ca6ca89759f8755108c9f60fba163deac11737ac"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "65a42d5b34a4820d893c7de2cb9aadb83f7b4ae6"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "4e6ffa5114529d41a27c076330c58e5b57854b944e08792f34afc18c19eb034c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "5cafb8261f459bdaffc3a95242deb359374fd127"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "109e636ba7675750a1c5b9f1fb300b0c701a8aea51adea71e5441f79826aa2a2"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "cc0844b227ef0f308046acff2f1a7ba8646cec6a"
libgfortran_version = "3.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "f896a37464179396261afc226d51f58c0d40d60efc85d362dd1b13de0a251835"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "9faf7305c6f86266810d5db94eec8bcbe60e9621"
libgfortran_version = "4.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "9840c69454891331527d1c44f4db900d9a1ac07fceab1046f3dbd192ab406a63"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "4cd1d95d4eb536d8d89bc3af92f233c3f370716d"
libgfortran_version = "5.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "b35d3289cfefa45ab24ee52ece5075c55b61f2e6596a2d0af9c7a494e5ec0cd7"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.2.0+0/Libxc.v5.2.0.x86_64-w64-mingw32-libgfortran5.tar.gz"
