[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "ad7773353424e6da7eba8f76423fcf5fc8e14364"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "30a06f5231268a46ff5217977ca1f8c7ee638e6796545b1d70ad55cd49eaa95e"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.aarch64-linux-gnu.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "66b0f579443f8e5c9551140522faa74844969812"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "a6c8ac6b72f40f9d472c17b22369b025d9c884ab6b91a0ad2f59c639b431b0f0"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.aarch64-linux-musl.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5dc8baa1f14b49ec328e0a52faa3d79aeead11dd"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "25b05df296a2a51a16e65e58e11d3486b1bf73a90a053a270c2b99915614a524"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.armv7l-linux-gnueabihf.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "81230a8851def9ae39a395f577a77533f77b9a44"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "0a4d40f6d6b98eacad01775f5ceab277c225537c6e974dfc3362a164a1254add"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.armv7l-linux-musleabihf.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "2f9c8e7e94f415f054597f0b286dbeeb75e53585"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "4fba3c1ffd65f222daa9b550ffcdb8fd71b7d782c522d0a6c6080843c3643e54"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.i686-linux-gnu.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "63ce8f64903c4179933ca4e3e71ce42c474ebb25"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "a37d49d6055f615121dfd0e2d0fbc6b247ffa3629eb1f4ede4e8fbdf5cc877c9"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.i686-linux-musl.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "e88cd10ffeffe98db97f40fb24eaa57879a01e61"
os = "windows"

    [[Libxc.download]]
    sha256 = "7bb622b47d589dbce6a26b6818cd7ee3104d76c9be4361bc06b5f574ee297784"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.i686-w64-mingw32.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "aa72deb46535e0b795d20a2fc204a3fd992c8942"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "083c0933b80c12ac7316c7a7ec44b9413376d6106dfc2573e4afae5d1636e031"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.powerpc64le-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "1977f1caa52a94f2bdc80ecadc58305d61923988"
os = "macos"

    [[Libxc.download]]
    sha256 = "8d7d632cb19113cb8d553daa62b7e932eb47d35afa4c53a3134bdbc9cd75e6e5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.x86_64-apple-darwin.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "a6de85583c9e4f7ee6838055fe6a97f159dd6bdf"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "b8bdf198f86857b574cb31d773d371ddf63cfe506418e88944ac48aa6647f8a4"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.x86_64-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "361fa1ab4da8f89ec20b3ae53b4d48aed7e9858c"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "3e9edaa1591b7db6633853c908120ca2ae692de797e033518756f76aaca07b48"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.x86_64-linux-musl.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "736079de5c64725cb364c77ee3da591f6dac0c4e"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "ce4ae855e8b204a391f50ed9cdf477161938a66d85ebe5298974460614ea6030"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.x86_64-unknown-freebsd.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "db932d896e6b1ecb8c7234a0dd1b2befe3511ed2"
os = "windows"

    [[Libxc.download]]
    sha256 = "9115120d08efdc7c537d66c7060a2fcf194b46706e3a987ad093573ae357ca1b"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.0+0/Libxc.v5.1.0.x86_64-w64-mingw32.tar.gz"
