[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "8b3aabbe3bb8330bc2d614744c214cd482d021fd"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "280ff6be0c4852e86e6d234353609b8c260736d312dec8d32cf5bde9ebb11939"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.aarch64-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "d946861f37ea6864e191a5ef3f2128f683426e7b"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "19c2dd31e2772ee2fcfc7f07d898b532b0a3c5dcc76f6b52c988de2c221edaf8"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.aarch64-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "f6b43b89611e76389049303f8ac6e5225f9c80ea"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "fbbe6ebce886b54c804faf5f921eb35bba83ac11d3b3748a327f30da6372a674"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.aarch64-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "d792216f12e2611c7607f9009d83ce9597d705a9"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "9901381cfea212e212b1ec28ffd0f08ac6de00b49df8ad614780b6356cf6428c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.aarch64-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "cb3975d7668166b02b1e42e5ddb38c2049a95a3d"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "c2e16da26b0d0da04adb21a4125511d8f7ebb3ef9be334b5aab89fb77f8caaad"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.aarch64-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "c7be2c5fa23591708942b3d7c2f22be168d38729"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "006a9ac4bdfea9d15da55a99c1e5a3ccbb2beb1e4056678c4ced12b82d7de115"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.aarch64-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "98ee389928b484aebc97000dd486465f56a4bc3a"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "ce72f158e184d56f09f621a86b819711052b515a5499b7d2231963eb5be1c61d"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.armv7l-linux-gnueabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "75d9da726309ff4c14d22958baaa61da85875b52"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "baa93df776dce491aac736130800160dd02ec1d1c3a8e0aab5caa5f5ce8deec4"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.armv7l-linux-gnueabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "288ba44875d7bb613206e4d08bbb5306e796c087"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "ac5ad3a407e125c17ca266f558d2b2d0348b962dd910f6a42d9832b1f0352674"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.armv7l-linux-gnueabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "85567011797ad9e8fc8cdfd8cc357b8e8db58cb6"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "6ec22481f1b229f128d34628be90ba2dbfa15d5ffc0eced50199d130c1bf4765"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.armv7l-linux-musleabihf-libgfortran3.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "d0fa5f11da427973fcc206e11ad2c0cdfc03b565"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "a1858bb3792a8a7c99241590d5969e3d873fb5222c6048a7606e2e7713cc1cfa"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.armv7l-linux-musleabihf-libgfortran4.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "e99ed8ec0005ddb39fd728251e3dd6b269e12ca5"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "f8c485beaf1c0830172e4de710bc102b715d64b96cb8f75e405c37162c786366"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.armv7l-linux-musleabihf-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "28c78efb5643d30849fd91a0b04d5249a1290939"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "d08dd3f6abcabc6c9ab9504b496c3b7e2612381ea63b1c68a3a22d1052c2dbee"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.i686-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "855030d9655463736a381c736201e2b6ef7e30f2"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "2253c98a33fa7cc346a3046ddfb688af35ad209e9a1b1d819bd8f2a3ad03fec0"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.i686-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "5f76fcd61944018aff8c23d739d25c272464b362"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "f25a252e0f64b2b5ca2d4bd6203b57c396dff440642fea936c0acd73b586e0cb"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.i686-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "cf570d10a472fe5c2a5a2b026b27499655f4ff7f"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "d566c3a99fea3e6796043414be67e6c82210df2272697a457e2c1c0fbffeca83"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.i686-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "75006fa9bdfb04679e0a33a3404cd3a41006cda6"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "c972f8286baa5154cd453028f465e53ef50fc2da39240b670617b463c972ee59"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.i686-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "0cb7cc1711a34f6e5cc937e37ca91b3fe28ee39f"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "a2e73ebb1eb9591c67334f1ed1c6ae8c030c586e786430113ec2ef45a0b0c123"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.i686-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "ee2b97f8e2d68ee04217a060068082872968c34c"
libgfortran_version = "3.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "1d2b6624f4ad2bc9ff30de848e4064e79d75c997328c21479336f328b776739a"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.i686-w64-mingw32-libgfortran3.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "7a544c33703209a0b8df72a176bfa5290eb89307"
libgfortran_version = "4.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "0192b9b4580a0537f9029dadc721104e8ff2a265ac88446c5fe6ef826ce74972"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.i686-w64-mingw32-libgfortran4.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "268bfb33e44464375cd40a3b7de5b12690e98572"
libgfortran_version = "5.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "a7ec1ccf6c4a9de80177b5aa538b781a680cb18cef73215ad749021a2b5c7ebe"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.i686-w64-mingw32-libgfortran5.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "b1c449ae7689d08cffca7f18837a127e60c24376"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "526755d674238894e92a5bb4d538e3ef03824d2573b8be4cfb2f9e3c08ed0500"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.powerpc64le-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "35aa2bb2fba91ef54cf190e3cb159445c814e94f"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "027f56d9bbd7bdc9b97c2eeb8ab1c96634ab59ffc8404007723c826a6201e234"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.powerpc64le-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "7a708158132418a5cb23619533e848f211918b68"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "c62995d60bcd0f47ede4e6eff868a2ac787ae7d14eaf40e5ce91762df0771b22"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.powerpc64le-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "194e59115de0b72d6e3abfc18f70b43208a6f33c"
libgfortran_version = "3.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "fcc94d41996313e824b24c682a8f4095be775ad82c6ac20c1bd6ca37168412f5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-apple-darwin-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "e68a05f7b6f873282df99df69f99bbaac83c19ac"
libgfortran_version = "4.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "5bd8f044cd729f72e5117aeb9a18ed46cb3d6c4584f34af26469c2fc354b0f3b"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-apple-darwin-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "57d85e2d03505f8a8fde0635bb80e1a3919a78a2"
libgfortran_version = "5.0.0"
os = "macos"

    [[Libxc.download]]
    sha256 = "82e620ea8222778696221d9d0a836eead6920237990c825fb2b354202b361be0"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-apple-darwin-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "377152e036e8dc8ec9b63a6b9d10ebb151173195"
libc = "glibc"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "ec78cdf9f2cedd390c271e35fde7a334c131ccc2df2e53bf38f854376e504d5b"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-linux-gnu-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "518aad2b35142e90185eb1c56bf74f7e06ecf227"
libc = "glibc"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "4f92416399b5d7f33c73faaed9f6e74db5f8d8d8c8562cc332ec0f17e315b33c"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-linux-gnu-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "39b5ad2562453ee44f65b1c4430f863d406592ae"
libc = "glibc"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "a9a771886cdc83809dffa6bea1b8198f257cb18b085ec1f528855494c747b6a8"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-linux-gnu-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "59e7c7fa001738e499e7338bae7c4b31c7119599"
libc = "musl"
libgfortran_version = "3.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "9a02a4f8d3634e387ac6f53c3b3a1102c2059258a7092500160c972e8b7ff1bb"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-linux-musl-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "338ff36cff0776473f07465aa9611dffebdd3fed"
libc = "musl"
libgfortran_version = "4.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "b22e2af3338b8db1aeaa16e8903b81deac799c3541bd0ded007ed8672eec63c7"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-linux-musl-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "14a3fb131b9322a875564864f7c59c8412dfa44c"
libc = "musl"
libgfortran_version = "5.0.0"
os = "linux"

    [[Libxc.download]]
    sha256 = "de914140908849563dca5c597b12ecf76d14f9fcdbfe759b6ba7dfbc9d9ebf1a"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-linux-musl-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "0cbf49b742a9c2c674e29a2ef50a342c2633f10f"
libgfortran_version = "3.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "d42ae68aee9c318f03f1805204da07fdaa5fcccd761a1e67d90e6bca4b42e687"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-unknown-freebsd-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "bfe352f34b8168d50a0fa7cc79f6fc212ebe8dc2"
libgfortran_version = "4.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "9e34d9de5ce1c2620b5f927ddc602090afd7d9bf69ab9cb15bef330511fadedd"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-unknown-freebsd-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "721fd1469fef3e13efa030a2b4e4dca4af0b86f0"
libgfortran_version = "5.0.0"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "73f374767212a0e7e967be559fbaea66068b2500c4f28abc4905a4a30e81eb32"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-unknown-freebsd-libgfortran5.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "921241b01a037312d7786beeebeb7279649356ac"
libgfortran_version = "3.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "447ae7ced2e17344e78ce3c03f3011be9f4819ffdd5e098d257452b1cbc98e48"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-w64-mingw32-libgfortran3.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "be4a80a28e7ec7b17dea3a88cca7cbf7129373b2"
libgfortran_version = "4.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "7cfedf36707656e035c29c13e22ccf6b38e1951bb8aaaf77e45bd5aee954f308"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-w64-mingw32-libgfortran4.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "693cab83737be79db530647e5a0f1157dd5063fb"
libgfortran_version = "5.0.0"
os = "windows"

    [[Libxc.download]]
    sha256 = "0573e7617039fa76a1b153f1f495349212de4a0e2120d9c7f45b8111f530dd4f"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.1.5+1/Libxc.v5.1.5.x86_64-w64-mingw32-libgfortran5.tar.gz"
