[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "e9ef5b0391385725725cd970364ab05dfa8d8d22"
os = "macos"

    [[Libxc.download]]
    sha256 = "eabd0d2f408d2ab309a66473838011e40f421c66cc529a09fca34350cb75832f"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.aarch64-apple-darwin.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "66adc5baff997f95725d997898cc7a4ab136b379"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "87e51467d68f5a3739f19292a987e8423569c8001afeed9527bf41ffe5650372"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.aarch64-linux-gnu.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "34df440c1e34405c58285f50ba09945e41f01924"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "94526d26f2317817500513c2c06745c708c2ac5d7c6335421cc88f310eb493d9"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.aarch64-linux-musl.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "2a22c9a0392eb78eb16c9001bf06b34987de21f1"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "9fc02725697e30b06221879854b840fde7edb56f7d2f1d9d3a5312cfb4f53725"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.armv6l-linux-gnueabihf.tar.gz"
[[Libxc]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "32b434d60886abfa7eca9fbaa15c2669053f2c56"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "65088f36b34f9f8f6bc3afd42b41cf4b4420a50d27fa27ffad52e8327ca1f915"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.armv6l-linux-musleabihf.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "7c86d601f60e92570e44b05a0c0f4fe4e3ebed5e"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "5c077d80624f3a60878b9fd6424d8efc660ea0c72b94986445bd608b5a5fc9ce"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.armv7l-linux-gnueabihf.tar.gz"
[[Libxc]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "1702fd33b4809fd9db6b3fe9a889b1f55f5beed2"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "4eb3a18bf9972b31efab3c0af5709d784738e842a7122596e399f54610425d72"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.armv7l-linux-musleabihf.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "ff989146ab5fdc6cc333af1fb047c8ca9744b776"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "58351510de69082569f90603afb0bfc5bc00f02484703c1d571fc7db80b29388"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.i686-linux-gnu.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "1d58d3abff75e2e194f73901deb3f7a449f59d85"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "c28b8a4118a38a39edbaf313e93ec3284965d667982e88ef10c983ecb21613ca"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.i686-linux-musl.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "2159bdcd83b8d4700c9e8775a450901599904336"
os = "windows"

    [[Libxc.download]]
    sha256 = "e067500975a8d60d787dffbf24955c913d03e21c7d244ef553a5580c1945f740"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.i686-w64-mingw32.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "5a89ee4f00d9b3827a01574050b6f8a168b14299"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "7f21f3826c797556f10c8273ca1dea53832abc51bc3edd82f6954e74ac6dfddc"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.powerpc64le-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "ba3e9ca741ab4e3814bc35d627351a01cff2fda5"
os = "macos"

    [[Libxc.download]]
    sha256 = "69ff3b091aae9b23de4158b802d844e3f579126d0b347d8beab211c307778f26"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.x86_64-apple-darwin.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "eb89c8a78aa5acaeed955188e158912b1e213879"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "4f4244b19d7f4e0ed1661d0e9c90c41ce766fe8fe480eaecf7bc7b118ba083d1"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.x86_64-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "b00356446e2b11cb4673036a6f719baf3e8e9fea"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "74f33ffdf6ede1124e07c1e7dd8628bd1725d0e91765c11e54a7f60a87b3d35d"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.x86_64-linux-musl.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "dd4742f60783b25ef6ad0de07a57300715333dc1"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "7050ad3e9e122f590ebddcdc43e01baaf27469a50b9eaa6c2507c910f99b6559"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.x86_64-unknown-freebsd.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "5b66b353f770b6e96df882dfe7cc410c70e2231f"
os = "windows"

    [[Libxc.download]]
    sha256 = "40ba002057796dacdae26711129e3343cf364a7a4f2bbe48296b652ce33d7600"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v6.0.0+1/Libxc.v6.0.0.x86_64-w64-mingw32.tar.gz"
