[[Libxc]]
arch = "i686"
git-tree-sha1 = "d04dd5b32cf82d0cabb06713ad26597061ccf95e"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "c000395d40fe6ec9fd5e8d6567da37dc95039c0493be7594c38ab61413f57dc0"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+0/Libxc.v5.0.0.i686-linux-musl.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "55793e0bc44109e72e39bf37fab227be3e122968"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "c2e0fbc5b9961ecd8703ee0ebc9accaec23dfba0d4d6b804fa34bf1f8f903fd9"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+0/Libxc.v5.0.0.aarch64-linux-musl.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "139f16797e8849d30bc30a16edda065f7001e6e3"
os = "windows"

    [[Libxc.download]]
    sha256 = "4b54269eaf9a121613da9d2e3404bb32b1629dd45b54dc6e75d4691d9187b67d"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+0/Libxc.v5.0.0.i686-w64-mingw32.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "2156ed036e9801176a1d7c129d3184588c381881"
os = "windows"

    [[Libxc.download]]
    sha256 = "04d5daa8ae00d239ec2d9835433dfd9f1849267d6636ddc3eddf9affc07806bb"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+0/Libxc.v5.0.0.x86_64-w64-mingw32.tar.gz"
[[Libxc]]
arch = "i686"
git-tree-sha1 = "050c5860679bc7c2d30e827a07cedd39192532fe"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "0e26341121acd753da259e7f290d3b6fb28fbdf9e1dab55d12ce397f9b7466e5"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+0/Libxc.v5.0.0.i686-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "72a66fbb20164ba41d9d4f315b1543bd33e84040"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "ab93332b8139dba31d7639b68e0efa25aff15a59b278a5846ebfa959a9f9b032"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+0/Libxc.v5.0.0.x86_64-linux-gnu.tar.gz"
[[Libxc]]
arch = "powerpc64le"
git-tree-sha1 = "0ba45ebadd3215ee91567bf3ca78095d840ad738"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "ec3e3884dbaef77eef2ec72461576dedb1195dbc4e425e3ba05856784ce09ca0"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+0/Libxc.v5.0.0.powerpc64le-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "c1c901c8a4e30ff7190d9bff99f3beb49732dca8"
os = "macos"

    [[Libxc.download]]
    sha256 = "feb3e0d5b2aca56b1918b6c85ec900b68f58e5137e3fb5729aded1f02d9cb6c3"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+0/Libxc.v5.0.0.x86_64-apple-darwin14.tar.gz"
[[Libxc]]
arch = "aarch64"
git-tree-sha1 = "f03d9f3efadcffa07fe57d4fb62a55e6611a2af8"
libc = "glibc"
os = "linux"

    [[Libxc.download]]
    sha256 = "afe633c2803845452f3f7cdf1dedb95e0fc533d24ff50168a49d05c4736cf22d"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+0/Libxc.v5.0.0.aarch64-linux-gnu.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "1e3dc5fe27b18fe6d0fe95ddbdf8398ab8b2bf9d"
os = "freebsd"

    [[Libxc.download]]
    sha256 = "858c5ac998ef5614158f27ec717a3a7b851158d4bd562ae8e6ecb7e79790cab4"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+0/Libxc.v5.0.0.x86_64-unknown-freebsd11.1.tar.gz"
[[Libxc]]
arch = "x86_64"
git-tree-sha1 = "ee3acf0f7b1877b44d8b2b82ceca434e91c7fc4f"
libc = "musl"
os = "linux"

    [[Libxc.download]]
    sha256 = "66ba5b16fbb3d7bd71747cfcfd8967236a0bdd4262237dac8227a96f148425a7"
    url = "https://github.com/JuliaBinaryWrappers/Libxc_jll.jl/releases/download/Libxc-v5.0.0+0/Libxc.v5.0.0.x86_64-linux-musl.tar.gz"
